# Numpy Exercise

#### 1. Import the numpy package under the name as np  

In [ ]:
import numpy as np

#### 2. Print the numpy version and the configuration 

In [ ]:
print(np.__version__)
print(np.show_config())

1.18.5
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
None


#### 3. Create a null vector of size 10

In [ ]:
a=np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array

In [ ]:
b=np.size(a)
print("size of an array:\n",b)

size of an array:
 10


#### 5.  How to get the documentation of the numpy add function from the command line? 

In [ ]:
np.add?

#### 6.  Create a null vector of size 10 but the fifth value which is 1

In [ ]:
c=np.zeros(10)
c[4]=1
print(c)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49

In [ ]:
d=np.arange(10,50)
print(d)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last)

In [ ]:
print(np.arange(49,9,-1))

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
e=np.arange(0,9).reshape(3,3)
print(e)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\]

In [ ]:
li=np.array([1,2,0,0,4,0])
print(np.where(li !=0))


(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix

In [ ]:
print(np.identity(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values

In [ ]:
g=np.random.random((3,3,3))
print(g)

[[[0.95807675 0.35797924 0.13906248]
  [0.80194767 0.58739703 0.76327444]
  [0.20988798 0.73545267 0.69691855]]

 [[0.69572978 0.27744546 0.60795133]
  [0.54193625 0.60206651 0.18210708]
  [0.88141083 0.02403726 0.07261533]]

 [[0.9203175  0.7166812  0.36469742]
  [0.66863546 0.4350537  0.70601638]
  [0.51939264 0.55872873 0.30957004]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [ ]:
x=np.random.random((10,10))
print(x)
print("minimum value is")
print(np.min(x))
print("maximum value is")
print(np.max(x))

[[0.96819948 0.61934713 0.80614578 0.17467317 0.10997049 0.98222221
  0.86508164 0.95198719 0.4752364  0.5872091 ]
 [0.33523875 0.24025588 0.98816309 0.62552012 0.67994452 0.22362295
  0.07318461 0.09937382 0.43547707 0.32696742]
 [0.77040001 0.59247361 0.44521227 0.671556   0.71518481 0.74039796
  0.83986248 0.12195263 0.16255189 0.29081867]
 [0.17474336 0.31348121 0.06539682 0.40747023 0.26787605 0.42986527
  0.856654   0.94344023 0.02567528 0.5897683 ]
 [0.87359987 0.58234749 0.4050225  0.27889308 0.02980644 0.26793542
  0.55237089 0.67777877 0.03557967 0.80084378]
 [0.32220086 0.28742734 0.90274496 0.33959652 0.03965864 0.64165242
  0.75933534 0.2047848  0.05373703 0.23007559]
 [0.70984866 0.15798    0.23910786 0.24487359 0.6480821  0.38227435
  0.2498096  0.18898179 0.82457529 0.66144853]
 [0.81245774 0.4722679  0.57348513 0.49100141 0.87980433 0.23945829
  0.67660932 0.01435452 0.82659248 0.11827089]
 [0.90459101 0.78066227 0.67631452 0.57624189 0.32795163 0.47308225
  0.83865107

#### 14. Create a random vector of size 30 and find the mean value

In [ ]:
rand=np.random.random((10,3))
print(rand)
m=np.mean(rand)
print("mean value is:{}".format(m))

[[0.23421018 0.50478006 0.91322316]
 [0.51420903 0.75489353 0.75084741]
 [0.19427257 0.93215709 0.0279612 ]
 [0.1720182  0.27203108 0.6822665 ]
 [0.05298035 0.86241184 0.5266343 ]
 [0.71829134 0.25225666 0.97749439]
 [0.50903272 0.1701279  0.27906278]
 [0.63313181 0.02337611 0.76601579]
 [0.8083015  0.25383373 0.58288842]
 [0.6868634  0.33167695 0.64274066]]
mean value is:0.5009996884537968


#### 15. Create a 2d array with 1 on the border and 0 inside

In [ ]:

k=np.full((5,5),1)
print(k)
k[1:-1,1:-1]=0
print("\n",k)



[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]

 [[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


#### 16. How to add a border (filled with 0's) around an existing array?

In [ ]:
y=np.arange(10,22).reshape(3,4)
print("\n",y)
y[0,:]=0
y[-1,:]=0
y[:,0]=0
y[:,-1]=0
print("\n",y)


 [[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]

 [[ 0  0  0  0]
 [ 0 15 16  0]
 [ 0  0  0  0]]


#### 17. What is the result of the following expression?

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [ ]:
p = np.diag(1+np.arange(4),k=-1)
print(p)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [ ]:
v=np.zeros((8,8))
v[1::2,::2] = 1
v[::2,1::2] = 1
print(v)


[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [ ]:
print (np.unravel_index(100, (6,7,8)))

(1, 5, 4)
