# ARRAY INTRO

In [2]:
import numpy as np


In [7]:
a=np.array([[1,2,3],[4,5,6]])
print (a)

[[1 2 3]
 [4 5 6]]


In [8]:
a=np.array((1,2,3))
print(a)

[1 2 3]


In [10]:
a=np.zeros((3,4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [20]:
d = np.full((3, 3), 6, dtype = 'complex')
print(d)

[[6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]]


In [23]:
d=np.random.random((2,2))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [25]:
d=np.arange(0,72,8)
print(d)

[ 0  8 16 24 32 40 48 56 64]


In [28]:
g = np.linspace(0, 5, 5)
print(g)

[0.   1.25 2.5  3.75 5.  ]


In [53]:
a=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(a )
print("reshaped array is")
new=a.reshape(2,2,3)
print(new)
print("flattened array is")
flat=a.flatten()
print(flat)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
reshaped array is
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
flattened array is
[ 1  2  3  4  5  6  7  8  9 10 11 12]


# ARRAY INDEXING

In [70]:
a = np.array([[-1, 2, 0, 4],
                [4, -0.5, 6, 0],
                [2.6, 0, 7, 8],
                [3, -7, 4, 2.0]])
slicing=a[1:3,::3]
print("sliced array is \n {}".format(slicing))
b=a[[0,1,2,3],[3,2,1,0]]
print("element at indices (0,3):\n",b)
print("printing elements greater than 2")
conda=a>2
temp=a[conda]
print(temp)

sliced array is 
 [[4.  0. ]
 [2.6 8. ]]
element at indices (0,3):
 [4. 6. 0. 3.]
printing elements greater than 2
[4.  4.  6.  2.6 7.  8.  3.  4. ]


# SOME BASICS

In [82]:
a=np.array([1,2,3,4,5,6])
print(a)
print("adding 3 to all the elements in  the array:",a+3)
print("subtracting 1 from all the elements in  the array:",a-1)
print("on multiplying each element with 2:",a*3)
a*=4
print("modifying the original array ",a)
a=np.array([[1,2],[2,3],[4,5]])
print("new array  is:\n",a)
print("transpose of the array  is:\n",a.T)



[1 2 3 4 5 6]
adding 3 to all the elements in  the array: [4 5 6 7 8 9]
subtracting 1 from all the elements in  the array: [0 1 2 3 4 5]
on multiplying each element with 2: [ 3  6  9 12 15 18]
modifying the original array  [ 4  8 12 16 20 24]
new array  is:
 [[1 2]
 [2 3]
 [4 5]]
transpose of the array  is:
 [[1 2 4]
 [2 3 5]]


# OPERATORS

In [93]:
a = np.array([[1, 2], 
              [3, 4]])
b = np.array([[5, 6], 
              [6, 7]])
print("sum:\n",a+b)
print("difference:\n",a-b)
print("multiplication:\n",a*b)
print("matrix multiplication:\n",a.dot(b))
print("exponent of a:\n",np.exp(a))
print("square root of a is:\n ",np.sqrt(b))
print("sin of a is :\n",np.sin(a))



sum:
 [[ 6  8]
 [ 9 11]]
difference:
 [[-4 -4]
 [-3 -3]]
multiplication:
 [[ 5 12]
 [18 28]]
matrix multiplication:
 [[17 20]
 [39 46]]
exponent of a:
 [[ 2.71828183  7.3890561 ]
 [20.08553692 54.59815003]]
square root of a is:
  [[2.23606798 2.44948974]
 [2.44948974 2.64575131]]
sin of a is :
 [[ 0.84147098  0.90929743]
 [ 0.14112001 -0.7568025 ]]


# Sorting Arrays

In [104]:
a = np.array([[1, 4, 2],
              [5, 4,6],
              [10, -1, 9]])
print("elements in sorted order:\n",np.sort(a,axis=None))
print("row wise sort:\n",np.sort(a,axis=1))
print("column wise sort:\n",np.sort(a,axis=0))
column_name=[("Name","S10"),("grad_y",int),("cgpa",float)]
values = [('Hrithik', 2009, 8.5), ('Ajay', 2008, 8.7), ('Pankaj', 2008, 7.9), ('Aakash', 2009, 9.0)]
a=np.array(values,column_name)
print("array sorted by names:\n",np.sort(a,order="Name"))
print("array sorted by graduation year and then cgpa",np.sort(a,order=["grad_y","cgpa"]))




elements in sorted order:
 [-1  1  2  4  4  5  6  9 10]
row wise sort:
 [[ 1  2  4]
 [ 4  5  6]
 [-1  9 10]]
column wise sort:
 [[ 1 -1  2]
 [ 5  4  6]
 [10  4  9]]
array sorted by names:
 [(b'Aakash', 2009, 9. ) (b'Ajay', 2008, 8.7) (b'Hrithik', 2009, 8.5)
 (b'Pankaj', 2008, 7.9)]
array sorted by graduation year and then cgpa [(b'Pankaj', 2008, 7.9) (b'Ajay', 2008, 8.7) (b'Hrithik', 2009, 8.5)
 (b'Aakash', 2009, 9. )]


# Stacking and Splitting

In [111]:
a = np.array([[1, 2],
              [9, 10]])

b = np.array([[5, 12],
              [11, 8]])
print("vertical stacking:\n",np.vstack((a,b)))
print("horizontal stacking:\n",np.hstack((a,b)))             
c=[21,22]
print("column stack:\n",np.column_stack((b,c)))             
print("concatenate:\n",np.concatenate((a,b),1))             
a = np.array([[1, 3, 5, 7, 9, 11],
              [2, 4, 6, 8, 10, 12]])
print("split horizontal in 2 parts",np.hsplit(a,2))
print("split in vertical in 2 parts", np.vsplit(a,3))
print ("arry_split",np.arr_split(a,1))

      

vertical stacking:
 [[ 1  2]
 [ 9 10]
 [ 5 12]
 [11  8]]
horizontal stacking:
 [[ 1  2  5 12]
 [ 9 10 11  8]]
column stack:
 [[ 5 12 21]
 [11  8 22]]
concatenate:
 [[ 1  2  5 12]
 [ 9 10 11  8]]


# Some more functions

In [117]:
a = np.array([[1,12,31,4],[7,16,12,0]])
print(a)
print("min in whole array",np.min(a))
print("min in whole row",np.min(a,1))
print("min in whole column",np.min(a,0))
a = np.array([[1,12,31,4],[7,16,12,0]])
print(a)
print("max in whole array",np.max(a))
print("max in whole row",np.max(a,1))
print("max in whole column",np.max(a,0))
c = np.array([1,5,4,2,0])
print("median",np.median(c))
print("mean",np.mean(c))
print("average",np.average(c))





[[ 1 12 31  4]
 [ 7 16 12  0]]
min in whole array 0
min in whole row [1 0]
min in whole column [ 1 12 12  0]
[[ 1 12 31  4]
 [ 7 16 12  0]]
max in whole array 31
max in whole row [31 16]
max in whole column [ 7 16 31  4]
median 2.0
mean 2.4
average 2.4
